/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LedgersRouteImport } from './routes/ledgers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillsIndexRouteImport } from './routes/bills.index'
import { Route as MastersVendorsRouteImport } from './routes/masters.vendors'
import { Route as MastersItemsRouteImport } from './routes/masters.items'
import { Route as MastersFixedAssetsRouteImport } from './routes/masters.fixed-assets'
import { Route as MastersCustomersRouteImport } from './routes/masters.customers'
import { Route as MastersCompaniesRouteImport } from './routes/masters.companies'
import { Route as BillsNewRouteImport } from './routes/bills.new'
import { Route as BillsIdRouteImport } from './routes/bills.$id'

const LedgersRoute = LedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIndexRoute = BillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersVendorsRoute = MastersVendorsRouteImport.update({
  id: '/masters/vendors',
  path: '/masters/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersItemsRoute = MastersItemsRouteImport.update({
  id: '/masters/items',
  path: '/masters/items',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersFixedAssetsRoute = MastersFixedAssetsRouteImport.update({
  id: '/masters/fixed-assets',
  path: '/masters/fixed-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersCustomersRoute = MastersCustomersRouteImport.update({
  id: '/masters/customers',
  path: '/masters/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersCompaniesRoute = MastersCompaniesRouteImport.update({
  id: '/masters/companies',
  path: '/masters/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsNewRoute = BillsNewRouteImport.update({
  id: '/bills/new',
  path: '/bills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIdRoute = BillsIdRouteImport.update({
  id: '/bills/$id',
  path: '/bills/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ledgers': typeof LedgersRoute
  '/bills/$id': typeof BillsIdRoute
  '/bills/new': typeof BillsNewRoute
  '/masters/companies': typeof MastersCompaniesRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/fixed-assets': typeof MastersFixedAssetsRoute
  '/masters/items': typeof MastersItemsRoute
  '/masters/vendors': typeof MastersVendorsRoute
  '/bills/': typeof BillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ledgers': typeof LedgersRoute
  '/bills/$id': typeof BillsIdRoute
  '/bills/new': typeof BillsNewRoute
  '/masters/companies': typeof MastersCompaniesRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/fixed-assets': typeof MastersFixedAssetsRoute
  '/masters/items': typeof MastersItemsRoute
  '/masters/vendors': typeof MastersVendorsRoute
  '/bills': typeof BillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ledgers': typeof LedgersRoute
  '/bills/$id': typeof BillsIdRoute
  '/bills/new': typeof BillsNewRoute
  '/masters/companies': typeof MastersCompaniesRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/fixed-assets': typeof MastersFixedAssetsRoute
  '/masters/items': typeof MastersItemsRoute
  '/masters/vendors': typeof MastersVendorsRoute
  '/bills/': typeof BillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ledgers'
    | '/bills/$id'
    | '/bills/new'
    | '/masters/companies'
    | '/masters/customers'
    | '/masters/fixed-assets'
    | '/masters/items'
    | '/masters/vendors'
    | '/bills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ledgers'
    | '/bills/$id'
    | '/bills/new'
    | '/masters/companies'
    | '/masters/customers'
    | '/masters/fixed-assets'
    | '/masters/items'
    | '/masters/vendors'
    | '/bills'
  id:
    | '__root__'
    | '/'
    | '/ledgers'
    | '/bills/$id'
    | '/bills/new'
    | '/masters/companies'
    | '/masters/customers'
    | '/masters/fixed-assets'
    | '/masters/items'
    | '/masters/vendors'
    | '/bills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LedgersRoute: typeof LedgersRoute
  BillsIdRoute: typeof BillsIdRoute
  BillsNewRoute: typeof BillsNewRoute
  MastersCompaniesRoute: typeof MastersCompaniesRoute
  MastersCustomersRoute: typeof MastersCustomersRoute
  MastersFixedAssetsRoute: typeof MastersFixedAssetsRoute
  MastersItemsRoute: typeof MastersItemsRoute
  MastersVendorsRoute: typeof MastersVendorsRoute
  BillsIndexRoute: typeof BillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ledgers': {
      id: '/ledgers'
      path: '/ledgers'
      fullPath: '/ledgers'
      preLoaderRoute: typeof LedgersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/': {
      id: '/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof BillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/vendors': {
      id: '/masters/vendors'
      path: '/masters/vendors'
      fullPath: '/masters/vendors'
      preLoaderRoute: typeof MastersVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/items': {
      id: '/masters/items'
      path: '/masters/items'
      fullPath: '/masters/items'
      preLoaderRoute: typeof MastersItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/fixed-assets': {
      id: '/masters/fixed-assets'
      path: '/masters/fixed-assets'
      fullPath: '/masters/fixed-assets'
      preLoaderRoute: typeof MastersFixedAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/customers': {
      id: '/masters/customers'
      path: '/masters/customers'
      fullPath: '/masters/customers'
      preLoaderRoute: typeof MastersCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/companies': {
      id: '/masters/companies'
      path: '/masters/companies'
      fullPath: '/masters/companies'
      preLoaderRoute: typeof MastersCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/new': {
      id: '/bills/new'
      path: '/bills/new'
      fullPath: '/bills/new'
      preLoaderRoute: typeof BillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$id': {
      id: '/bills/$id'
      path: '/bills/$id'
      fullPath: '/bills/$id'
      preLoaderRoute: typeof BillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LedgersRoute: LedgersRoute,
  BillsIdRoute: BillsIdRoute,
  BillsNewRoute: BillsNewRoute,
  MastersCompaniesRoute: MastersCompaniesRoute,
  MastersCustomersRoute: MastersCustomersRoute,
  MastersFixedAssetsRoute: MastersFixedAssetsRoute,
  MastersItemsRoute: MastersItemsRoute,
  MastersVendorsRoute: MastersVendorsRoute,
  BillsIndexRoute: BillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
